# Use the official SQL Server image
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables (change these as needed)
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Admin

# Expose the SQL Server port
EXPOSE 1433